# Generated by Django 6.0.3 on 2026-03-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='total_applications',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
