# Generated by Django 6.0.3 on 2026-03-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_category_options_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveJob',
            fields=[
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('jobs.job',),
        ),
        migrations.CreateModel(
            name='ExpiredJob',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('jobs.job',),
        ),
        migrations.CreateModel(
            name='FeaturedJob',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('jobs.job',),
        ),
        migrations.AddField(
            model_name='job',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
